name: Lint and Format Python Code

on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black autoflake
        
    - name: Trigger Jenkins Pipeline
      if: ${{ success() }}
      uses: appleboy/jenkins-action@master
      with:
        url: ${{ secrets.NGROK_URL }}
        job: 'cd-pipeline'
        user: ${{ secrets.JENKINS_USERNAME }}
        token: ${{ secrets.JENKINS_TOKEN }}
